version: '3.8'
services:
  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    logging:
      driver: none
    environment:
      MYSQL_DATABASE: mysqltests
      MYSQL_ALLOW_EMPTY_PASSWORD: yes
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: psycarlo
      MYSQL_PASSWORD: bitcoinislove
    ports:
      - '3306:3306'
  mongo:
    image: mongo
    logging:
      driver: none
    environment:
      MONGO_INITDB_DATABASE: mongotests
      MONGO_INITDB_ROOT_USERNAME: psycarlo
      MONGO_INITDB_ROOT_PASSWORD: bitcoinislove
    ports:
      - '27017:27017'
  integration:
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      MONGO_CONNECTION_STRING: mongodb://psycarlo:bitcoinislove@mongo:27017
      MONGO_DATABASE: psytests
      WAIT_HOSTS: mongo:27017, mysql:3306
    depends_on:
      - mongo
      - mysql
