version: '3.8'
services:
  mongo:
    image: mongo
    ports:
      - '27017:27017'
    logging:
      driver: none
    environment:
      MONGO_INITDB_DATABASE: psytests
      MONGO_INITDB_ROOT_USERNAME: psycarlo
      MONGO_INITDB_ROOT_PASSWORD: bitcoinislove
    volumes:
      - ./data/mysql:/var/lib/mysql
  mysql:
    image: mysql
    ports:
      - '3306:3306'
    logging:
      driver: none
    environment:
      MYSQL_INITDB_ROOT_PASSWORD: bitcoinislove
    volumes:
      - ./data/mongo:/data/db
  integration:
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      MONGO_CONNECTION_STRING: mongodb://psycarlo:bitcoinislove@mongo:27017
      MONGO_DATABASE: psytests
      WAIT_HOSTS: mongo:27017, mysql:3306
    depends_on:
      - mongo
      - mysql
